# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SATIApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SATIApp

  # Your 'node_modules' directory is probably in the root of your project,
 # but if not, adjust the `:path` accordingly
 pod 'React', :path => '../node_modules/react-native', :subspecs => [
   'Core',
   'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
   'RCTText',
   'RCTNetwork',
   'RCTWebSocket', # needed for debugging
   # Add any other subspecs you want to use in your project
 ]

 pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'

 # # Third party deps podspec link
 #  pod 'Ionicons', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'

  target 'SATIAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SATIApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SATIApp-tvOS

  target 'SATIApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
