platform :ios, '8.0'
target 'SATIApp' do
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
pod 'GoogleMaps'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

end
